#📘**Talento Tech: Data Analytics con Python**
#Pre-entrega

**Alumno:** Daniel Matías Ozan

**Instructura:** Gisele Gonzalez

**Tutor Pedagógico:** Cristian Urquiza

## ❗ Antes que nada...
Importamos las librerias y creamos las funciones que utilizaremos mas adelante.

In [1]:
#Importamos las librerias a utilizar
import pandas as pd
import os
from google.colab import drive

In [13]:
#Funcion para el Analisis Exploratorio

def analisis_exploratorio(df):
  print("Informacion del DataFrame:\n")
  print(df.info())
  print("\n")
  print("Descripcion estadistica del DataFrame:\n")
  print(df.describe())
  print("\n")
  print("Dimensiones del DataFrame:\n")
  print(df.shape)
  print("\n")
  print("Columnas del DataFrame:\n")
  print(df.columns)
  print("\n")
  print("Tipos de datos del DataFrame:\n")
  print(df.dtypes)
  print("\n")

#Funcion para analizar identificar datos duplicados y nulos
def calidad_datos(df):
  print("Valores Nulos en el Data Frame:\n")
  print(df.isna().sum())
  print("\nDuplicados en el Data Frame:\n")
  print(df.duplicated().sum())

#Funcion para eliminar caracteres no deseados

def normalizar_datos(df):
  for columna in df.columns:
    if df[columna].dtype == 'object':
      df[columna] = df[columna].str.strip()
      df[columna] = df[columna].str.replace('"', '')
      df[columna] = df[columna].str.replace(r"[\u200b\t\r\n]", "", regex=True)
      df[columna] = df[columna].str.replace(" +", " ", regex=True)
      df[columna] = df[columna].str.title()
  return df

#Funcion para normalizar fechas

def normalizar_fechas(df):
  for columna in df.columns:
    if 'fecha' in columna.lower():
      df[columna] = pd.to_datetime(df[columna], errors="coerce", dayfirst=True)
  return df

## 🧩 Etapa 1: Recopilación y Preparación de Datos

### 1️⃣ Carga de datos

In [3]:
#Hacemos la coneccion a nuestro drive
drive.mount('/content/drive')
mis_datasets = '/content/drive/MyDrive/datasets'

#Listamos los archivos cargados en la carpeta "datasets"
lista_csv = os.listdir(mis_datasets)
print(lista_csv)

Mounted at /content/drive
['ventas.csv', 'clientes.csv', 'marketing.csv']

In [6]:
#Cargamos los archivos solicitados en la actividad: Ventas, Clientes y Marketing
ventas = pd.read_csv(f'{mis_datasets}/{lista_csv[0]}')
clientes = pd.read_csv(f'{mis_datasets}/{lista_csv[1]}')
marketing = pd.read_csv(f'{mis_datasets}/{lista_csv[2]}')

In [7]:
#Visualisamos los primeros datos de las tablas cargadas

print("Tabla Ventas: \n", ventas.head(),"\n")

print("Tabla Clientes:\n" ,clientes.head(),"\n")

print("Tabla Marketing:\n" ,marketing.head())

Tabla Ventas:
    id_venta           producto   precio  cantidad fecha_venta  \
0       792  Cuadro decorativo   $69.94       5.0  02/01/2024
1       811    Lámpara de mesa  $105.10       5.0  02/01/2024
2      1156           Secadora   $97.96       3.0  02/01/2024
3      1372           Heladera  $114.35       8.0  02/01/2024
4      1546           Secadora  $106.21       4.0  02/01/2024

           categoria
0         Decoración
1         Decoración
2  Electrodomésticos
3  Electrodomésticos
4  Electrodomésticos

Tabla Clientes:
    id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

Tabla Marketing:
    id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

### 2️⃣ Análisis exploratorio inicial

In [8]:
#Analisis Exploratorio Ventas

analisis_exploratorio(ventas)

Informacion del DataFrame:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     3035 non-null   int64
 1   producto     3035 non-null   object
 2   precio       3033 non-null   object
 3   cantidad     3033 non-null   float64
 4   fecha_venta  3035 non-null   object
 5   categoria    3035 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 142.4+ KB
None


Descripcion estadistica del DataFrame:

          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000


Dimensiones del DataFrame:

(3035, 6)


Columnas del DataFrame:

Index(['id_venta', 'producto', 'precio', 'cantidad', 'fecha_venta',
       'categoria'],
      dtype='object')


Tipos de datos del DataFrame:

id_venta         int64
producto        object
precio          object
cantidad       float64
fecha_venta     object
categoria       object
dtype: object

In [ ]:
#Analisis Exploratorio Clientes

analisis_exploratorio(clientes)

Informacion del DataFrame:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  567 non-null    int64
 1   nombre      567 non-null    object
 2   edad        567 non-null    int64
 3   ciudad      567 non-null    object
 4   ingresos    567 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 22.3+ KB
None


Descripcion estadistica del DataFrame:

       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000


Dimensiones del DataFrame:

(567, 5)


Columnas del DataFrame:

Index(['id_cliente', 'nombre', 'edad', 'ciudad', 'ingresos'], dtype='object')


Tipos de datos del DataFrame:

id_cliente      int64
nombre         object
edad            int64
ciudad         object
ingresos      float64
dtype: object

In [ ]:
#Analisis Exploratorio Marketing

analisis_exploratorio(marketing)

Informacion del DataFrame:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_campanha   90 non-null     int64
 1   producto      90 non-null     object
 2   canal         90 non-null     object
 3   costo         90 non-null     float64
 4   fecha_inicio  90 non-null     object
 5   fecha_fin     90 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.3+ KB
None


Descripcion estadistica del DataFrame:

       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000


Dimensiones del DataFrame:

(90, 6)


Columnas del DataFrame:

Index(['id_campanha', 'producto', 'canal', 'costo', 'fecha_inicio',
       'fecha_fin'],
      dtype='object')


Tipos de datos del DataFrame:

id_campanha       int64
producto         object
canal            object
costo           float64
fecha_inicio     object
fecha_fin        object
dtype: object

###Comentarios:

Las tablas fueron cargadas con exito. Pero se observa que multiples columnas de los data frames presentan como tipo de dato `object` cuando deberian ser de otro tipo. Esto puede indicar que hay un problema de calidad de datos. Por lo que se deberia analizar eso antes de pasar a analisis posteriores.

### 3️⃣ Calidad de los datos

In [9]:
calidad_datos(ventas)

Valores Nulos en el Data Frame:

id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64

Duplicados en el Data Frame:

35

In [10]:
calidad_datos(clientes)

Valores Nulos en el Data Frame:

id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64

Duplicados en el Data Frame:

0

In [11]:
calidad_datos(marketing)

Valores Nulos en el Data Frame:

id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64

Duplicados en el Data Frame:

0

###Comentarios:
Se observan datos duplicados y nulos en el data frame de Ventas.
Especificamente se identifican datos nulos en las columnas precios y cantidad. Y 35 datos duplicados.

## 🧹 Etapa 2: Preprocesamiento y Limpieza de Datos
**Objetivo:** Demostrar conocimiento de las técnicas de limpieza y transformación de datos.

### 4️⃣ Limpieza de datos

In [12]:
#Eliminacion de duplicados
ventas = ventas.drop_duplicates()
clientes = clientes.drop_duplicates()
marketing = marketing.drop_duplicates()

In [14]:
#Normalizamos datos
ventas_clean = normalizar_datos(ventas)
clientes_clean = normalizar_datos(clientes)
marketing_clean = normalizar_datos(marketing)

In [15]:
#Normalizamos fechas

ventas_clean = normalizar_fechas(ventas_clean)
clientes_clean = normalizar_fechas(clientes_clean)
marketing_clean = normalizar_fechas(marketing_clean)

In [16]:
#Eliminamos los carecteres no desados en la columna precios de la tabla ventas
ventas_clean['precio'] = ventas_clean['precio'].str.replace('$', '').str.replace(',', '').astype(float)
ventas_clean.dtypes

id_venta                int64
producto               object
precio                float64
cantidad              float64
fecha_venta    datetime64[ns]
categoria              object
dtype: object

In [17]:
#Revisamos si los tipos de columnas están OK

print(f'Ventas:\n{ventas_clean.dtypes}\n')
print(f'Clientes:\n{clientes_clean.dtypes}\n')
print(f'Marketing:\n{marketing_clean.dtypes}')

Ventas:
id_venta                int64
producto               object
precio                float64
cantidad              float64
fecha_venta    datetime64[ns]
categoria              object
dtype: object

Clientes:
id_cliente      int64
nombre         object
edad            int64
ciudad         object
ingresos      float64
dtype: object

Marketing:
id_campanha              int64
producto                object
canal                   object
costo                  float64
fecha_inicio    datetime64[ns]
fecha_fin       datetime64[ns]
dtype: object

In [40]:
#guardamos los csv limpios

ventas_clean.to_csv(f'{mis_datasets}/ventas_clean.csv', index=False)
clientes_clean.to_csv(f'{mis_datasets}/clientes_clean.csv', index=False)
marketing_clean.to_csv(f'{mis_datasets}/marketing_clean.csv', index=False)

### 5️⃣ Transformación de datos

In [ ]:
# TODO: Aplicar filtros y transformaciones para crear una tabla de ventas
# que muestre solo los productos con alto rendimiento. calcular el percentil 80
# y filtrar los productos que superen ese umbral en ventas.
#quantile(0.8)
# Sugerencia: usar .query() o condiciones con operadores lógicos.

In [30]:
ventas_clean = ventas_clean.assign(ingreso = ventas_clean['precio'] * ventas_clean['cantidad'])
ventas_clean.sort_values(by='ingreso', ascending=False).head(5)

,id_venta,producto,precio,cantidad,fecha_venta,categoria,ingreso
550,2063,Smartphone,124.01,12.0,2024-03-05,Electrónica,1488.12
912,1109,Batidora,123.83,12.0,2024-04-11,Electrodomésticos,1485.96
866,2373,Smartphone,123.60,12.0,2024-04-07,Electrónica,1483.20
2345,2703,Smartphone,123.40,12.0,2024-10-03,Electrónica,1480.80
513,1569,Batidora,122.02,12.0,2024-02-29,Electrodomésticos,1464.24

In [36]:
resumen_ventas = (ventas_clean.
                  groupby('producto', dropna=False, as_index=False, observed=False)
                  .agg(
                      ingreso_total = ('ingreso', 'sum'),
                      total_unidades= ('cantidad', 'sum'),
                      precio_promedio= ('precio', 'mean'))
                  )

print(resumen_ventas.sort_values('ingreso_total', ascending=False))

                  producto  ingreso_total  total_unidades  precio_promedio
19         Lámpara De Mesa       82276.38          1112.0        72.720625
3              Auriculares       74175.58           958.0        76.302727
20              Microondas       72562.89           912.0        79.176000
5                 Cafetera       59607.31           765.0        79.046581
9        Cuadro Decorativo       54297.60           726.0        74.578000
26              Smartphone       54132.44           665.0        81.398416
25                Secadora       52115.45           696.0        73.338900
16       Jarrón Decorativo       51130.88           672.0        74.534000
4                 Batidora       50979.20           672.0        77.537200
24       Rincón De Plantas       50456.45           691.0        74.823861
13      Freidora Eléctrica       50155.15           630.0        78.251300
2               Aspiradora       50085.86           651.0        77.447400
15         Horno Eléctrico       49913.90           633.0        75.688800
18                Lavadora       48946.44           671.0        74.953400
23               Proyector       48187.00           626.0        74.680404
0          Adorno De Pared       48093.49           633.0        76.097800
27              Smartwatch       47836.86           620.0        75.535800
21     Parlantes Bluetooth       47779.46           660.0        73.583571
29               Televisor       47038.04           632.0        73.815300
12       Espejo Decorativo       46783.31           635.0        75.663300
17                  Laptop       46179.48           617.0        75.326200
7   Consola De Videojuegos       46174.41           623.0        76.346869
11   Elementos De Cerámica       45411.09           636.0        71.611515
10          Cámara Digital       45217.96           638.0        72.010700
22        Plancha De Vapor       45196.63           632.0        73.039200
8                 Cortinas       44865.03           610.0        73.649900
1                 Alfombra       44773.06           615.0        74.098300
28                  Tablet       25856.57           374.0        71.382586
14                Heladera       25736.80           330.0        74.127708
6               Candelabro       11128.80           160.0        74.595417

In [38]:
alto_rendimiento = resumen_ventas.query('ingreso_total')
resumen_ventas['ingreso_total'].quantile(0.80)

np.float64(52518.848000000005)

### 6️⃣ Agregación

In [ ]:
# TODO: Resumir las ventas por categoría de producto y analizar los ingresos generados.
# Sugerencia: usar .groupby() y .agg() para generar métricas como suma y promedio.

### 7️⃣ Integración de datos, opcional, NO OBLIGATORIO

In [ ]:
# TODO: Combinar los sets de datos de ventas y marketing para obtener una visión más amplia de las tendencias.
# Sugerencia: usar pd.merge() especificando la clave común entre ambos DataFrames.
# Documentar cualquier observación relevante sobre la combinación de datos.